Change enttyp logic
We were receiving a syntax error when running the tool on one of our GDB's

if enttype := detailed.xpath("enttyp"):
                  ^
SyntaxError: invalid syntax

I had to take a guess what the logic was actually supposed to be checking for, but I assumed it was meant to be !=. I made the change to the script and the tool stopped breaking.